### ISSUE TITLE
switch to composer-plugin

### ISSUE THREAD

**Issue by discordier** [ContaoBlackforest/contao-image-srcset#1]
You should rather depend on the composer-plugin instead of the deprecated composer-installer

**Comment by baumannsven** [comment]
is switch to composer-plugin

**Comment by discordier** [comment]
Depending on version `~2.0` would be better. :)

**Comment by baumannsven** [comment]
Erklärung bitte, bin noch nicht so der Held im Compooser

**Comment by discordier** [comment]
You have an unbound version dependency now.

Read https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

So it would be better to require `"contao-community-alliance/composer-plugin": "~2.0"` as 2.\* is the current stable major.
